"""
elliptic_lattice.py - Elliptic functions and double periodicity for 数学史記

Visualizes the discovery of elliptic functions by Abel (1827) and Jacobi (1827)
as doubly-periodic functions on the complex plane. Three function families are
contrasted: trigonometric (real period only), exponential (imaginary period only),
elliptic (both real and imaginary periods → lattice → torus).

Modes:
    trig_periodic    - sin(x) on real axis with one period 2π highlighted.
                       Fixed params: x range [-3π, 3π], amplitude 1.0,
                       highlighted period [0, 2π], color CYAN.
    exp_periodic     - Complex plane with horizontal strip [Im(z) ∈ (0, 2π)] shaded
                       to show that e^z has imaginary period 2πi.
                       Fixed params: z range x∈[-2,2], y∈[-2π, 2π], color PINK.
    elliptic_doubly  - Complex plane with parallelogram lattice generated by
                       ω_1 = (2.0, 0) and ω_2 = (0.5, 1.5). Lattice points colored
                       GOLD to indicate "same function value". One fundamental
                       parallelogram filled. Central formula f(z+ω_1) = f(z+ω_2) = f(z).
                       Fixed params: 5×5 lattice grid (m,n ∈ {-2..2}), ω_1=(2.0, 0),
                       ω_2=(0.5, 1.5).
    torus            - Parallelogram with paired-arrow edge identification (top/bottom
                       and left/right pairs glued) shown alongside a 2D-projected
                       torus icon. Caption explains "torus = quotient of complex plane
                       by lattice" → Riemann surface foundation.

Duration-aware: reads target duration from _manim_params.json.

Used by: Episode 020 (Abel), math pillar 3.
"""

import math

import numpy as np
from manim import (
    DOWN,
    LEFT,
    RIGHT,
    UP,
    Arrow,
    Axes,
    Circle,
    DashedLine,
    Dot,
    FadeIn,
    Line,
    MathTex,
    ParametricFunction,
    Polygon,
    Scene,
    Text,
    VGroup,
    config,
)
from style import (
    ACCENT_CYAN,
    ACCENT_GOLD,
    ACCENT_PINK,
    BG_COLOR,
    FONT,
    TEXT_DIM,
    TEXT_WHITE,
    load_params,
)

config.background_color = BG_COLOR

# Period values
TWO_PI = 2 * math.pi

# Subtitle safe zone: y > -2.0
SUBTITLE_Y_LIMIT = -2.0

# Lattice parameters for elliptic_doubly mode
OMEGA_1 = np.array([2.0, 0.0, 0.0])
OMEGA_2 = np.array([0.5, 1.5, 0.0])
LATTICE_RANGE = 2  # m, n in {-2..2} → 5x5 grid


class EllipticLattice(Scene):
    """Mode-branching scene for elliptic function periodicity visualization."""

    def construct(self):
        self.camera.background_color = BG_COLOR
        params = load_params()
        self._duration = params.get("duration", 25)
        mode = params.get("mode", "elliptic_doubly")

        if mode == "trig_periodic":
            self.build_trig_periodic()
        elif mode == "exp_periodic":
            self.build_exp_periodic()
        elif mode == "torus":
            self.build_torus()
        else:
            self.build_elliptic_doubly()

    # -------------------------------------------------------------------
    # Mode: trig_periodic — sin(x) with real period 2π
    # -------------------------------------------------------------------
    def build_trig_periodic(self):
        duration = self._duration

        # Title (y = 3.0)
        title = Text(
            "三角関数 ── 実周期のみ",
            font=FONT,
            font_size=30,
            color=ACCENT_CYAN,
        )
        title.move_to(np.array([0, 3.0, 0]))

        # Axes (x: −3π to 3π, y: −1.5 to 1.5). Scaled to fit screen.
        # x_range visually maps to about ±5.5 horizontally
        axes = Axes(
            x_range=[-3 * math.pi, 3 * math.pi, math.pi],
            y_range=[-1.5, 1.5, 0.5],
            x_length=11.0,
            y_length=2.4,
            tips=False,
            axis_config={"color": TEXT_DIM, "stroke_width": 1.5},
        )
        axes.move_to(np.array([0, 0.4, 0]))

        # sin curve
        sin_curve = axes.plot(
            lambda x: math.sin(x),
            x_range=[-3 * math.pi, 3 * math.pi, 0.05],
            color=ACCENT_CYAN,
            stroke_width=3,
        )

        # Highlight one period [0, 2π] with vertical dashed lines
        x0_screen = axes.coords_to_point(0, -1.5)[0]
        x1_screen = axes.coords_to_point(TWO_PI, -1.5)[0]
        y_top = axes.coords_to_point(0, 1.5)[1]
        y_bot = axes.coords_to_point(0, -1.5)[1]

        v_left = DashedLine(
            start=np.array([x0_screen, y_bot, 0]),
            end=np.array([x0_screen, y_top, 0]),
            color=ACCENT_GOLD,
            stroke_width=2,
        )
        v_right = DashedLine(
            start=np.array([x1_screen, y_bot, 0]),
            end=np.array([x1_screen, y_top, 0]),
            color=ACCENT_GOLD,
            stroke_width=2,
        )

        # Period arrow (between the two vertical lines, slightly below axes)
        arrow_y = y_bot - 0.15
        period_arrow = Arrow(
            start=np.array([x0_screen, arrow_y, 0]),
            end=np.array([x1_screen, arrow_y, 0]),
            color=ACCENT_GOLD,
            stroke_width=3,
            buff=0,
            max_tip_length_to_length_ratio=0.05,
        )
        period_label = MathTex(r"2\pi", font_size=32, color=ACCENT_GOLD)
        period_label.next_to(period_arrow, DOWN, buff=0.05)

        # Formula (y around -1.7, safely above subtitle zone)
        formula = MathTex(
            r"\sin(x + 2\pi) = \sin(x)",
            font_size=36,
            color=TEXT_WHITE,
        )
        formula.move_to(np.array([0, -1.85, 0]))

        # ===== Animation =====
        self.play(FadeIn(title), run_time=0.5)
        self.play(FadeIn(axes), run_time=0.6)
        self.play(FadeIn(sin_curve), run_time=1.2)
        self.wait(0.5)
        self.play(FadeIn(v_left), FadeIn(v_right), run_time=0.6)
        self.play(FadeIn(period_arrow), FadeIn(period_label), run_time=0.7)
        self.wait(0.5)
        self.play(FadeIn(formula), run_time=0.7)

        elapsed = 0.5 + 0.6 + 1.2 + 0.5 + 0.6 + 0.7 + 0.5 + 0.7
        remaining = max(0.5, duration - elapsed - 0.5)
        self.wait(remaining)

    # -------------------------------------------------------------------
    # Mode: exp_periodic — e^z with imaginary period 2πi
    # -------------------------------------------------------------------
    def build_exp_periodic(self):
        duration = self._duration

        title = Text(
            "指数関数 ── 虚周期のみ",
            font=FONT,
            font_size=30,
            color=ACCENT_PINK,
        )
        title.move_to(np.array([0, 3.0, 0]))

        # Complex plane: x range, y range in mathematical coords
        # We render the z-plane (input space)
        plane_x_range = [-2.5, 2.5]
        plane_y_range = [-3.5, 3.5]
        plane_x_len = 5.0
        plane_y_len = 4.5
        plane = Axes(
            x_range=plane_x_range + [1.0],
            y_range=plane_y_range + [math.pi],
            x_length=plane_x_len,
            y_length=plane_y_len,
            tips=False,
            axis_config={"color": TEXT_DIM, "stroke_width": 1.5},
        )
        plane.move_to(np.array([0, 0.3, 0]))

        # Axis labels
        re_label = MathTex(r"\mathrm{Re}(z)", font_size=22, color=TEXT_DIM)
        re_label.next_to(plane.x_axis.get_end(), RIGHT, buff=0.1)
        im_label = MathTex(r"\mathrm{Im}(z)", font_size=22, color=TEXT_DIM)
        im_label.next_to(plane.y_axis.get_end(), UP, buff=0.05)

        # Highlighted horizontal strip Im(z) ∈ [0, 2π]
        x_left_screen = plane.coords_to_point(plane_x_range[0], 0)[0]
        x_right_screen = plane.coords_to_point(plane_x_range[1], 0)[0]
        y_lo = plane.coords_to_point(0, 0)[1]
        y_hi = plane.coords_to_point(0, TWO_PI)[1]
        # Clamp y_hi to within plane
        y_hi_max = plane.coords_to_point(0, plane_y_range[1])[1]
        y_hi = min(y_hi, y_hi_max)

        strip = Polygon(
            np.array([x_left_screen, y_lo, 0]),
            np.array([x_right_screen, y_lo, 0]),
            np.array([x_right_screen, y_hi, 0]),
            np.array([x_left_screen, y_hi, 0]),
            color=ACCENT_PINK,
            stroke_width=1.5,
            fill_color=ACCENT_PINK,
            fill_opacity=0.18,
        )

        # Vertical arrow from origin to 2πi indicating the period
        period_arrow = Arrow(
            start=np.array([x_left_screen - 0.4, y_lo, 0]),
            end=np.array([x_left_screen - 0.4, y_hi, 0]),
            color=ACCENT_GOLD,
            stroke_width=3,
            buff=0,
            max_tip_length_to_length_ratio=0.08,
        )
        period_label = MathTex(r"2\pi i", font_size=30, color=ACCENT_GOLD)
        period_label.next_to(period_arrow, LEFT, buff=0.1)

        # Formula
        formula = MathTex(
            r"e^{z + 2\pi i} = e^z",
            font_size=36,
            color=TEXT_WHITE,
        )
        formula.move_to(np.array([2.5, -1.85, 0]))

        # Note: real period absent
        note = MathTex(
            r"e^{z + a} \neq e^z \quad (a \in \mathbb{R}, a \neq 0)",
            font_size=22,
            color=TEXT_DIM,
        )
        note.move_to(np.array([-2.0, -1.85, 0]))

        # ===== Animation =====
        self.play(FadeIn(title), run_time=0.5)
        self.play(FadeIn(plane), FadeIn(re_label), FadeIn(im_label), run_time=0.7)
        self.wait(0.4)
        self.play(FadeIn(strip), run_time=0.8)
        self.play(FadeIn(period_arrow), FadeIn(period_label), run_time=0.7)
        self.wait(0.5)
        self.play(FadeIn(formula), run_time=0.6)
        self.play(FadeIn(note), run_time=0.5)

        elapsed = 0.5 + 0.7 + 0.4 + 0.8 + 0.7 + 0.5 + 0.6 + 0.5
        remaining = max(0.5, duration - elapsed - 0.5)
        self.wait(remaining)

    # -------------------------------------------------------------------
    # Mode: elliptic_doubly — lattice on complex plane
    # -------------------------------------------------------------------
    def build_elliptic_doubly(self):
        duration = self._duration

        title = Text(
            "楕円関数 ── 二重周期",
            font=FONT,
            font_size=30,
            color=ACCENT_GOLD,
        )
        title.move_to(np.array([0, 3.05, 0]))

        # Lattice center (slightly below title)
        lattice_center = np.array([-2.5, 0.4, 0])

        # Draw lattice points: m * ω_1 + n * ω_2 for m, n ∈ {-LATTICE_RANGE..LATTICE_RANGE}
        # Use a screen-coord scale so lattice fits in the left half
        lattice_scale = 0.7

        def lattice_pt(m, n):
            return lattice_center + lattice_scale * (m * OMEGA_1 + n * OMEGA_2)

        dots = VGroup()
        for m in range(-LATTICE_RANGE, LATTICE_RANGE + 1):
            for n in range(-LATTICE_RANGE, LATTICE_RANGE + 1):
                p = lattice_pt(m, n)
                # Skip dots that would fall below subtitle zone
                if p[1] < -1.7:
                    continue
                if p[1] > 2.5:
                    continue
                if abs(p[0] - lattice_center[0]) > 3.5:
                    continue
                d = Dot(p, radius=0.07, color=ACCENT_GOLD)
                dots.add(d)

        # Draw lattice grid lines (faint)
        lines = VGroup()
        for m in range(-LATTICE_RANGE, LATTICE_RANGE + 1):
            start = lattice_pt(m, -LATTICE_RANGE)
            end = lattice_pt(m, LATTICE_RANGE)
            ln = Line(start=start, end=end, color=TEXT_DIM, stroke_width=1).set_opacity(0.4)
            lines.add(ln)
        for n in range(-LATTICE_RANGE, LATTICE_RANGE + 1):
            start = lattice_pt(-LATTICE_RANGE, n)
            end = lattice_pt(LATTICE_RANGE, n)
            ln = Line(start=start, end=end, color=TEXT_DIM, stroke_width=1).set_opacity(0.4)
            lines.add(ln)

        # Fundamental parallelogram (m=0..1, n=0..1) filled
        p00 = lattice_pt(0, 0)
        p10 = lattice_pt(1, 0)
        p11 = lattice_pt(1, 1)
        p01 = lattice_pt(0, 1)
        fund_para = Polygon(
            p00,
            p10,
            p11,
            p01,
            color=ACCENT_GOLD,
            stroke_width=2,
            fill_color=ACCENT_GOLD,
            fill_opacity=0.18,
        )

        # ω_1 and ω_2 vectors as arrows from origin
        omega1_arrow = Arrow(
            start=p00,
            end=p10,
            color=ACCENT_CYAN,
            stroke_width=4,
            buff=0,
            max_tip_length_to_length_ratio=0.12,
        )
        omega2_arrow = Arrow(
            start=p00,
            end=p01,
            color=ACCENT_PINK,
            stroke_width=4,
            buff=0,
            max_tip_length_to_length_ratio=0.12,
        )
        omega1_label = MathTex(r"\omega_1", font_size=28, color=ACCENT_CYAN)
        omega1_label.move_to((p00 + p10) / 2 + np.array([0, -0.32, 0]))
        omega2_label = MathTex(r"\omega_2", font_size=28, color=ACCENT_PINK)
        omega2_label.move_to((p00 + p01) / 2 + np.array([-0.32, 0, 0]))

        # Right-side panel: formula + caption
        formula = MathTex(
            r"f(z + \omega_1) = f(z + \omega_2) = f(z)",
            font_size=30,
            color=TEXT_WHITE,
        )
        formula.move_to(np.array([2.7, 1.0, 0]))

        caption = Text(
            "格子点はすべて同じ関数値",
            font=FONT,
            font_size=22,
            color=ACCENT_GOLD,
        )
        caption.move_to(np.array([2.7, 0.2, 0]))

        sub_caption = Text(
            "実周期と虚周期、両方を持つ",
            font=FONT,
            font_size=20,
            color=TEXT_DIM,
        )
        sub_caption.move_to(np.array([2.7, -0.4, 0]))

        # Bottom note
        bottom_note = Text(
            "Abel・Jacobi 1827年 独立並行発見",
            font=FONT,
            font_size=22,
            color=TEXT_WHITE,
        )
        bottom_note.move_to(np.array([0, -1.85, 0]))

        # ===== Animation =====
        self.play(FadeIn(title), run_time=0.5)
        self.play(FadeIn(lines), run_time=0.7)
        self.play(
            FadeIn(omega1_arrow),
            FadeIn(omega1_label),
            FadeIn(omega2_arrow),
            FadeIn(omega2_label),
            run_time=0.8,
        )
        self.wait(0.4)
        self.play(FadeIn(fund_para), run_time=0.7)
        self.wait(0.3)
        self.play(FadeIn(dots), run_time=1.0)
        self.wait(0.4)
        self.play(FadeIn(formula), run_time=0.7)
        self.play(FadeIn(caption), run_time=0.5)
        self.play(FadeIn(sub_caption), run_time=0.5)
        self.wait(0.5)
        self.play(FadeIn(bottom_note), run_time=0.6)

        elapsed = 0.5 + 0.7 + 0.8 + 0.4 + 0.7 + 0.3 + 1.0 + 0.4 + 0.7 + 0.5 + 0.5 + 0.5 + 0.6
        remaining = max(0.5, duration - elapsed - 0.5)
        self.wait(remaining)

    # -------------------------------------------------------------------
    # Mode: torus — parallelogram → torus identification
    # -------------------------------------------------------------------
    def build_torus(self):
        duration = self._duration

        title = Text(
            "楕円関数はトーラス上の関数",
            font=FONT,
            font_size=30,
            color=ACCENT_GOLD,
        )
        title.move_to(np.array([0, 3.05, 0]))

        # ----- Left: parallelogram with paired-arrow edge identification -----
        para_center = np.array([-3.5, 0.5, 0])
        scale = 0.85
        # Vertices of parallelogram (using same OMEGA_1, OMEGA_2)
        v00 = para_center
        v10 = para_center + scale * OMEGA_1
        v11 = para_center + scale * (OMEGA_1 + OMEGA_2)
        v01 = para_center + scale * OMEGA_2

        para = Polygon(
            v00,
            v10,
            v11,
            v01,
            color=ACCENT_GOLD,
            stroke_width=2.5,
            fill_color=ACCENT_GOLD,
            fill_opacity=0.12,
        )

        # Arrow markers on edges:
        # bottom (v00 → v10) and top (v01 → v11): same direction → "single arrow"
        # left (v00 → v01) and right (v10 → v11): same direction → "double arrow"
        def edge_arrow(start, end, double=False, color=ACCENT_CYAN):
            mid = (start + end) / 2
            direction = end - start
            length = np.linalg.norm(direction)
            unit = direction / length
            arrow_size = 0.22
            arrow = Arrow(
                start=mid - unit * arrow_size,
                end=mid + unit * arrow_size,
                color=color,
                stroke_width=3,
                buff=0,
                max_tip_length_to_length_ratio=0.5,
            )
            if double:
                # offset second arrow slightly to indicate double
                perp = np.array([-unit[1], unit[0], 0])
                arrow2 = Arrow(
                    start=mid - unit * arrow_size + perp * 0.15,
                    end=mid + unit * arrow_size + perp * 0.15,
                    color=color,
                    stroke_width=3,
                    buff=0,
                    max_tip_length_to_length_ratio=0.5,
                )
                return VGroup(arrow, arrow2)
            return arrow

        # bottom edge (single arrow, CYAN)
        bot_arrow = edge_arrow(v00, v10, double=False, color=ACCENT_CYAN)
        # top edge (single arrow, CYAN, same direction)
        top_arrow = edge_arrow(v01, v11, double=False, color=ACCENT_CYAN)
        # left edge (double arrow, PINK)
        left_arrow = edge_arrow(v00, v01, double=True, color=ACCENT_PINK)
        # right edge (double arrow, PINK, same direction)
        right_arrow = edge_arrow(v10, v11, double=True, color=ACCENT_PINK)

        para_label = Text(
            "基本平行四辺形",
            font=FONT,
            font_size=18,
            color=TEXT_DIM,
        )
        para_label.move_to(para_center + np.array([0.2, -1.3, 0]))

        # ----- Center: ≅ symbol -----
        cong_symbol = MathTex(r"\cong", font_size=64, color=TEXT_WHITE)
        cong_symbol.move_to(np.array([0, 0.7, 0]))

        glue_text = Text(
            "対辺を貼り合わせる",
            font=FONT,
            font_size=18,
            color=TEXT_DIM,
        )
        glue_text.move_to(np.array([0, -0.2, 0]))

        # ----- Right: torus icon (2D donut: outer ellipse + inner ellipse) -----
        torus_center = np.array([3.5, 0.5, 0])
        outer_ellipse = Circle(radius=1.4, color=ACCENT_GOLD, stroke_width=3)
        outer_ellipse.stretch(1.4, 0).stretch(0.85, 1)
        outer_ellipse.move_to(torus_center)

        inner_ellipse = Circle(radius=0.6, color=ACCENT_GOLD, stroke_width=2.5)
        inner_ellipse.stretch(1.4, 0).stretch(0.45, 1)
        inner_ellipse.move_to(torus_center + np.array([0, 0.05, 0]))

        # Torus shading hint: a single highlight curve
        highlight_curve = ParametricFunction(
            lambda t: (
                torus_center
                + np.array(
                    [
                        1.96 * math.cos(t),
                        0.85 * math.sin(t) + 0.0,
                        0,
                    ]
                )
            ),
            t_range=[math.pi * 0.05, math.pi * 0.95],
            color=ACCENT_CYAN,
            stroke_width=2,
        ).set_opacity(0.5)

        torus_label = Text(
            "トーラス",
            font=FONT,
            font_size=20,
            color=ACCENT_GOLD,
        )
        torus_label.move_to(torus_center + np.array([0, -1.25, 0]))

        torus_icon = VGroup(outer_ellipse, inner_ellipse, highlight_curve)

        # ----- Bottom note: connection to Riemann surface theory -----
        bottom_note = Text(
            "19世紀後半、リーマン面の理論の出発点となる",
            font=FONT,
            font_size=22,
            color=TEXT_WHITE,
        )
        bottom_note.move_to(np.array([0, -1.85, 0]))

        # ===== Animation =====
        self.play(FadeIn(title), run_time=0.5)
        self.play(FadeIn(para), run_time=0.7)
        self.play(
            FadeIn(bot_arrow),
            FadeIn(top_arrow),
            FadeIn(left_arrow),
            FadeIn(right_arrow),
            run_time=0.8,
        )
        self.play(FadeIn(para_label), run_time=0.4)
        self.wait(0.5)
        self.play(FadeIn(cong_symbol), FadeIn(glue_text), run_time=0.7)
        self.wait(0.4)
        self.play(FadeIn(torus_icon), run_time=0.9)
        self.play(FadeIn(torus_label), run_time=0.4)
        self.wait(0.5)
        self.play(FadeIn(bottom_note), run_time=0.6)

        elapsed = 0.5 + 0.7 + 0.8 + 0.4 + 0.5 + 0.7 + 0.4 + 0.9 + 0.4 + 0.5 + 0.6
        remaining = max(0.5, duration - elapsed - 0.5)
        self.wait(remaining)


# -----------------------------------------------------------------------
# SCENES dict for template auto-discovery
# -----------------------------------------------------------------------
# factual claims displayed in each mode. Aliases (list within list)
# allow Latin/kana variants — narration only needs to mention one alias.
LINT_FACTUAL_CLAIMS = {
    "trig_periodic": {"people": [], "years": []},
    "exp_periodic": {"people": [], "years": []},
    "elliptic_doubly": {
        "people": [
            ["アーベル", "Abel"],
            ["ヤコビ", "Jacobi"],
        ],
        "years": ["1827"],
    },
    "torus": {"people": [], "years": []},
}


SCENES = {
    "trig_periodic": {
        "class": "EllipticLattice",
        "params": {"mode": "trig_periodic"},
        "description": "sin(x) on real axis with period 2π — real period only",
    },
    "exp_periodic": {
        "class": "EllipticLattice",
        "params": {"mode": "exp_periodic"},
        "description": "e^z on complex plane with strip Im(z)∈[0,2π] — imaginary period 2πi only",
    },
    "elliptic_doubly": {
        "class": "EllipticLattice",
        "params": {"mode": "elliptic_doubly"},
        "description": "Lattice ω_1=(2.0,0), ω_2=(0.5,1.5) with f(z+ω_1)=f(z+ω_2)=f(z)",
    },
    "torus": {
        "class": "EllipticLattice",
        "params": {"mode": "torus"},
        "description": "Parallelogram with paired-arrow gluing ≅ torus → Riemann surface seed",
    },
}
