"""lint_portrait_reference.py - subject-portrait use_reference gap check

When a real photo/portrait of the episode subject exists (episode_config.json has a
non-empty `wikimedia_photo_urls`), the subject's ken_burns PORTRAIT scenes should set
`use_reference: true` (+ `is_subject: true`) so the image is generated by conditioning
on the real reference. If they are left UNSET, the script generator falls back to
text-only generation, which idealizes distinctive features: one episode
shipped a first cut with beards far too long and the glasses missing entirely,
exactly because the portrait scenes had use_reference/is_subject unset
(image-conditioning is far more faithful than text; see internal notes).

This static check (pre-images) flags subject portrait scenes that lack use_reference,
so the fix (set the flags + name the distinctive features) happens before the paid
Gemini image + the whole assemble/thumbnail chain is built on an idealized face.

Advisory (exit 0). --strict -> exit 1 when any WARN. Non-subject portraits (rivals),
which the convention tags is_subject:false / use_reference:false, are excluded.

Usage:
    python scripts/lint_portrait_reference.py examples/moriarty [--strict]
    python scripts/lint_portrait_reference.py examples/moriarty/scene_definition.json
"""

import argparse
import json
import os
import sys

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

# portrait-of-a-person markers in the (English) source_prompt
_PORTRAIT = "portrait"
_PERSON_MARKERS = (
    "beard",
    "mathematician",
    "scholar",
    "spectacles",
    "expression",
    "years old",
    "forehead",
    "clean-shaven",
    "moustache",
    "mustache",
    "his face",
    "hair",
)


def _resolve(path: str):
    """Return (scene_def_path, config_path) from an episode dir or a scene_def path."""
    if os.path.isdir(path):
        return (
            os.path.join(path, "scene_definition.json"),
            os.path.join(path, "episode_config.json"),
        )
    return path, os.path.join(os.path.dirname(path), "episode_config.json")


def _iter_scenes(scene_def: dict):
    for sec in scene_def.get("sections", []):
        yield from sec.get("scenes", [])


def _is_portrait_prompt(prompt: str) -> bool:
    p = (prompt or "").lower()
    return _PORTRAIT in p and any(m in p for m in _PERSON_MARKERS)


def _gate_on(config: dict) -> bool:
    """Reference gate: photos + birth_year (mirrors image_generator :1762 and the
    config_validator '参照 gate OFF' guard). When OFF (birth_year missing) EVERY
    subject portrait is text-only regardless of the per-scene flag -- that root
    cause is owned by the config_validator guard, not this lint."""
    return bool(config.get("wikimedia_photo_urls")) and bool(config.get("birth_year"))


def _effective_uses_reference(v: dict, gate_on: bool) -> bool:
    """Whether this person-scene ACTUALLY conditions on the reference photo.

    Mirrors image_generator exactly: use_reference DEFAULTS TO TRUE when unset
    (`v.get("use_reference", True)`), and the reference is applied only when the
    global gate is ON. So an UNSET (None) use_reference is reference-based when the
    gate is on -- treating None as "text-only" was the ある回 bug that false-flagged
    reference-based portraits (intro_03/person_05/closing_01). A person is assumed
    (callers gate on a portrait / young-person prompt, so has_person holds)."""
    if v.get("use_reference") is False:
        return False
    return gate_on


def run_lint(scene_path: str, config_path: str) -> list:
    """Return WARN dicts for subject portrait scenes missing use_reference."""
    with open(scene_path, encoding="utf-8") as f:
        scene_def = json.load(f)
    config = {}
    if os.path.exists(config_path):
        with open(config_path, encoding="utf-8") as f:
            config = json.load(f)

    # only relevant when a real reference photo exists for the subject
    photos = config.get("wikimedia_photo_urls") or []
    if not photos:
        return []
    gate_on = _gate_on(config)

    warnings = []
    for sc in _iter_scenes(scene_def):
        v = sc.get("visual") or {}
        if v.get("type") != "ken_burns":
            continue
        source_prompt = v.get("source_prompt", "")

        # NOTE: a lint that
        # flagged young/childhood scenes conditioned on an adult reference photo
        # (fear: the child renders with grown features) was added and then removed.
        # Empirically the image_generator's age handling renders children age-
        # appropriately even when conditioned on a much older reference: ある回
        # person_02 (explicit use_reference:true, "boy of about ten") AND ある回
        # Conway person_01 (unset, 11yo boy conditioned on a 68yo photo) both
        # shipped as proper children. So young+reference is NOT a reliable over-
        # aging signal -- the check had zero confirmed true positives and false-
        # flagged well-specified young scenes (Ramanujan/Turing/Lagrange/Conway).
        # ある回's first-cut over-aging was a WEAK-age-marker failure; the real fix
        # was emphatic age wording in the prompt ("MUST be a small CHILD of about
        # nine"), not use_reference:false. Same discipline as the ある回 天文
        # polyphone rejection: re-verify -> FPs on shipped -> do not ship.

        if not _is_portrait_prompt(source_prompt):
            continue
        # deliberate non-subject person (a rival) -> skip
        if v.get("is_subject") is False or v.get("use_reference") is False:
            continue
        # Subject portrait that does NOT effectively condition on the reference.
        # When the gate is ON, an unset (None) use_reference defaults to true and
        # IS reference-based, so it must NOT be flagged. This fires only when the scene is genuinely text-only despite
        # the subject having a reference photo -- i.e. the gate is OFF (birth_year
        # missing). The config_validator "参照 gate OFF" guard owns that root cause;
        # this adds the scene-level pointer.
        if v.get("use_reference") is not True and not _effective_uses_reference(v, gate_on):
            warnings.append(
                {
                    "type": "portrait_no_reference",
                    "scene_id": sc.get("scene_id"),
                    "note": (
                        "実写参照 (wikimedia_photo_urls) があるのに主題の肖像 ken_burns が "
                        "text-only 生成される。"
                        "参照 gate が OFF (config に birth_year が無い) 可能性が高い ── "
                        "config に birth_year を明記して gate を ON にする "
                        "(gate ON なら use_reference 未設定でも参照ベースになる)"
                    ),
                }
            )
    return warnings


def main():
    ap = argparse.ArgumentParser(description="subject-portrait use_reference gap check")
    ap.add_argument("path", help="episode dir or scene_definition.json")
    ap.add_argument("--strict", action="store_true", help="exit 1 if any WARN")
    args = ap.parse_args()

    scene_path, config_path = _resolve(args.path)
    if not os.path.exists(scene_path):
        print(f"[portrait-ref] scene_definition.json not found: {scene_path}")
        return 0
    warns = run_lint(scene_path, config_path)
    if not warns:
        print("[portrait-ref] OK: 主題肖像は参照を適切に条件付け (or 参照写真なし)")
        return 0
    print(f"[portrait-ref] WARN: {len(warns)} 件 (参照設定の要確認)")
    for w in warns:
        print(f"    {w['scene_id']} [{w['type']}]: {w['note']}")
    return 1 if args.strict else 0


if __name__ == "__main__":
    sys.exit(main())
